### ISSUE TITLE
How to use/install this?

### ISSUE THREAD

**Issue by kkmuffme** [Automattic/go-search-replace#21]
I downloaded the release but then what?
Could you add some infos to the readme, would be greatly appreciated!

**Comment by joshbetz** [comment]
`go-search-replace <from> <to>` replaces `from` with `to`.

The `go-search-replace` binary takes a SQL file as `STDIN` and outputs to `STDOUT`.

You may want to pipe data to `STDIN` (`cat file | go-search-replace`) and redirect the `STDOUT` stream to a file (`go-search-replace > other-file`).

You can put all these together to get the example from the README:

```
cat example-from.com.sql | search-replace example-from.com example-to.com > example-to.com.sql
```

**Comment by kkmuffme** [comment]
Thanks, but that was clear :-)

Somehow I didn't realize it's a binary, as I somehow just saw the .go.
For others having this basic issue just run:

```
wget https://github.com/Automattic/go-search-replace/releases/download/0.0.5/go-search-replace_linux_amd64.gz
gunzip go-search-replace_linux_amd64.gz
mv go-search-replace_linux_amd64 /usr/bin/go-search-replace
chmod 775 /usr/bin/search-replace
```

Then you can use it like the above command.
