### ISSUE TITLE
Help clarify understanding of async processing?

### ISSUE THREAD

**Issue by nathanielks** [Automattic/go-search-replace#22]
Hey there!

I was hoping you could help clarify my understanding of what's going on under the hood! I'm not terribly familiar with Go and am using your script as a method of learning! As I understand it, you're actually doing some clever asynchronous programming here and I wanted to make sure my understanding is correct 😄 

There's essentially two top-level goroutines: one that iterates over the file from STDIN and another that waits for the first goroutine to complete its work. The first goroutine creates child goroutines to process each line of the file separately. Now, this introduces a challenge: how can you asynchronously process a file but spit it out in the same order it was received? I believe that's why you have a channel of channels (`lines`). The child goroutine adds a channel for each line it processes (which is processed in order), which then allows the child goroutine to take as long as it likes because the channel will be read later once the file is finished being read and the WaitGroup is closed? _Or_ each line will be printed whenever it's received by [`fmt.Print()` on line 113](https://github.com/Automattic/go-search-replace/blob/b84814649c94297bb1d4cadab2c710bc975838b7/search-replace.go#L113)? Generally, the idea of the channel of channels allows you process each line individually asynchronously while still maintaining the order of the file. Is that understanding correct? Thanks for sharing this work, it's been incredibly helpful for me!

**Comment by nathanielks** [comment]
Another question for you! I'm curious why the WaitGroup waits in another goroutine as opposed to being in the main thread? I know the `main()` waits for `lines` to be read completely before exiting, which I don't quite understand. I know `main()` doesn't wait for goroutines to complete without being explicit about it, so does the final `for line := range lines` block execution which in effect allows the goroutines to complete?

**Comment by joshbetz** [comment]
Hi! Your description is all basically correct.

> Another question for you! I'm curious why the WaitGroup waits in another goroutine as opposed to being in the main thread?

That goroutine ensures we close the channel when we're done with it. If the waitGroup waited on the main thread, execution would be blocked after we put 10 lines in the queue because they'd never be read out by

https://github.com/Automattic/go-search-replace/blob/b84814649c94297bb1d4cadab2c710bc975838b7/search-replace.go#L112-L114

**Comment by nathanielks** [comment]
Got it! Thanks @joshbetz 😄
