### ISSUE TITLE
Unnecessary cat usage

### ISSUE THREAD

**Issue by kkmuffme** [Automattic/go-search-replace#23]
You suggest to use:

```
cat example-from.com.sql | search-replace example-from.com example-to.com > example-to.com.sql
```

but it's unnecessary to use cat here.
Better use:

```
< example-from.com.sql search-replace example-from.com example-to.com > example-to.com.sql
```

See: https://en.wikipedia.org/wiki/Cat_(Unix)#Useless_use_of_cat

**Comment by joshbetz** [comment]
True, but I think it's easier to read for most people with `cat`?

**Comment by kkmuffme** [comment]
Since this is even referenced in Wikipedia (to my surprise), this can be assumed to be common knowledge though (which means the readability is the same)
