### ISSUE TITLE
Add Support for Apple M1 chips

### ISSUE THREAD

**Issue by jblz** [Automattic/go-search-replace#27]
We should start adding releases for: Platform: `darwin`, Arch: `arm`

**Comment by jblz** [comment]
Maybe as simple as adding an arm architecture here:

https://github.com/Automattic/go-search-replace/blob/d99c5b45d3b3c870b1bad186941a3688a452d491/Makefile#L8

**Comment by joshbetz** [comment]
I think `darwin-arm64` support is supposed to be added in Go 1.16
