### ISSUE TITLE
Use golang phpserialize package?

### ISSUE THREAD

**Issue by nickchomey** [Automattic/go-search-replace#42]
I wonder if it could be useful to use one of these packages for doing the serialization rather than purely via regex stuff?

https://github.com/elliotchance/phpserialize
https://github.com/trim21/go-phpserialize
 
([here](https://github.com/trim21/go-phpserialize/issues/53) is what the 2nd package had to say about the differences between the two. The 1st is probably more relevant to `go-search-replace`)

I suppose it would probably be a lot slower to identify, parse and re-insert the serialized strings...

**Comment by abdullah-kasim** [comment]
Fixed in #43 .
