### ISSUE TITLE
UTF-8 Stress Test

### ISSUE THREAD

**Issue by mjangda** [Automattic/go-search-replace#7]
To help catch weird edge cases, is it worthwhile making sure that we have wider test coverage with sample from the following link?

https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-test.txt

**Comment by joshbetz** [comment]
We currently don't allow any of those characters, but we'll definitely have to add tests as we widen the allowed characters. I'm going to close this for now because I think it's self-explanatory enough to add relevant tests if we decide to allow more characters.
